sudo: required
services:
  - docker

before_install:
  - docker build -t d1ma-angel/docker-react -f Dockerfile.dev .

script:
  - docker run d1ma-angel/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react1"
  env: "docker-react1"
  bucket_name: "elasticbeanstalk-us-east-1-372196462942"
  bucket_path: "docker-react1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
